export default function getAllProducts() {
  return [
    {
      id: 'Eiger-Reveal-25-FMEN-001',
      slug: 'Eiger-Reveal-25-men',
      name: 'Eiger Reveal 25 Laptop Backpack',
      category: 'Men',
      price: 500_000,
      stock: 100,
      imageUrl: '/assets/images/Eiger Reveal 25 Laptop Backpack.jpg',
      description: `Bersiaplah untuk kembali menjalani rutinitas harian kamu dengan menggunakan tas Reveal 25. Bagian depan tas backpack pria dari EIGER Mountaineering ini memiliki kompartemen sekunder yang mudah diakses untuk menyimpan barang bawaan kamu dengan rapi. Bagian utama memiliki saku berlapis busa untuk menyimpan laptop 14 inci. Bagian samping memiliki dua saku tambahan untuk botol dan satu saku gantung untuk menyimpan barang yang sering diakses dengan cepat.`,
    },
    {
      id: 'Eiger-Escapade-20-WS-FMEN-002',
      slug: 'Eiger-Escapade-20-WS-men',
      name: 'Eiger Escapade 20 WS',
      category: 'Women',
      price: 700_000,
      stock: 5,
      imageUrl: '/assets/images/Eiger Escapade 20 WS.jpg',
      description: `Bawa semua perlengkapan harian Anda dengan nyaman menggunakan ransel Escapade 20 WS. Hadir dengan bukaan not;roll-top untuk mengakses kompartemen utama lebih leluasa yang dilengkapi saku dalam untuk menaruh dokumen. Terdapat dua saku botol dan saku di bagian depan untuk memudahkan Anda mengambil barang yang membutuhkan akses cepat. Dimension: 28 x 18 x 45 cm (Vol 20L) Material:Polyester 300DPolyester 600DPolyester 200D Recycled Lining Fitur:Lapisan dalam (lining) tas menggunakan bahan daur ulang.Kompartemen utama dengan saku dalam untuk menyimpan dokumen.Saku depan.Dua saku samping.Tali dada.Tali bahu dirancang secara ergonomis agar pas dipakai mengikuti bentuk tubuh wanita.`,
    },
    {
      id: 'Eiger-Crux-16-Basic-Daypack-FWOMEN-003',
      slug: 'Eiger-Crux-16-Basic-Daypack-women',
      name: 'Eiger Crux 16 Basic Daypack',
      category: 'Women',
      price: 700_000,
      stock: 0,
      imageUrl: '/assets/images/eiger Crux 16 Basic Daypack.jpeg',
      description: `Pastikan barang-barang bawaan kamu tetap aman dengan Crux 16. Tas backpack dari EIGER Mountaineering ini berkapasitas 16 liter dan dilengkapi dengan kompartemen utama, saku depan, dan dua saku samping untuk menyimpan barang bawaan kamu ahar tetap aman dan rapi..`,
    },
    {
      id: 'CEiger-Lorentz25-laptop-Backpack-FWOMEN-004',
      slug: 'Eiger-Lorentz25-laptop-Backpack-women',
      name: 'Eiger Lorentz 25 Laptop Backpack',
      category: 'Women',
      price: 700_000,
      stock: 7,
      imageUrl: '/assets/images/Eiger Lorentz25 Laptop Backpack.jpeg',
      description: `Lorentz adalah backpack berkapasitas 25 liter yang dirancang untuk menemani Anda beraktivitas sehari-hari. Dilengkapi fitur kompartemen utama dengan saku dalam yang dapat memuat keperluan harian Anda. Tas ini juga memiliki kompartemen khusus untuk menyimpan laptop berukuran hingga 15 yang dilengkapi dengan bantalan untuk melindungi laptop dari benturan. Saku depan dan dua saku samping yang dapat digunakan untuk menyimpan aksesoris tambahan. Detail aksen reflektif pada tas ini membantu Anda agar mudah terllihat dalam keadaan minim cahaya atau malam hari.Fitur:- Kompartemen utama dengan saku dalam untuk menyimpan dokumen- Kompartemen khusus laptop berukuran hingga 15- Saku depan dengan organizer dan gantungan kunci- Dua saku samping- Aksen reflektif, agar mudah terlihat dalam keadaan minim cahaya atau malam hari- Rain cover untuk melindungi tas dari air hujan- Tali dada`,
    },
    {
      id: 'Eiger-ZCrux16-BackpackFWOMEN-005',
      slug: 'Eiger-ZCrux16-Backpack-women',
      name: 'Eiger Z Crux 16 Backpack',
      category: 'Women',
      price: 900_000,
      stock: 100,
      imageUrl: '/assets/images/Eiger Z Crux 16 Backpack.jpeg',
      description: `Pastikan barang-barang bawaan kamu tetap aman dengan Crux 16. Tas backpack dari EIGER Mountaineering ini berkapasitas 16 liter dan dilengkapi dengan kompartemen utama, saku depan, dan dua saku samping untuk menyimpan barang bawaan kamu ahar tetap aman dan rapi..`,
    },
  ];
}
